spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

#    指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml